### ISSUE TITLE
why $1?

### ISSUE THREAD

**Issue by RobinTournemenne** [Devzstudio/Vscode-Emoji-Snippets#4]
I was wondering why you add $1 to each item of the snippet list? I removed them all to get a cleaner snippet insertion to my point of view.

**Comment by PJijin** [comment]
The cursor will be at that position. When you add snippet there will be one space automatically added and the cursor will be at next place.😃

**Comment by RobinTournemenne** [comment]
It does the same thing without the $1 on my setup. With the $1 on my setup, the cursor is also in selection mode, which messes with everything.

**Comment by PJijin** [comment]
No issues here. Do you use any custom settings that detail with $1? Can you please send more details about the issue that you are facing.
