### ISSUE TITLE
Can't enable the usage of emojis in my vscode

### ISSUE THREAD

**Issue by FatTonyy** [Devzstudio/Vscode-Emoji-Snippets#5]
"editor.quickSuggestions.comments": true
it doesn't work in my comments even after inputting the above code in my settings.json file

**Comment by FatTonyy** [comment]
nevermind I fixed it

**Comment by manokimbr** [comment]
worked with

"editor.quickSuggestions" : true

**Comment by manokimbr** [comment]
try
 "editor.quickSuggestions" : true
